### ISSUE TITLE
 [Feature Request] Add wobble as a animation 

### ISSUE THREAD

**Issue by killertofus** [allusive-dev/picom-allusive#1]

**Comment by allusive-dev** [comment]
Hey,
So, I have only ever coded in `C` once.
But I don't really have any projects at the moment So i will see what I can do about this.
If it wasn't clear in the repository README, I only copied the files exactly from pijulius repo so I could publish the package back on the AUR (after pijulius package was taken down for some reason).

I'll keep you updated on my progress.

**Comment by allusive-dev** [comment]
Also can you provide some more details about what this "wobble" animation would look like and what kind of animation it is.

**Comment by killertofus** [comment]
example of what kde does https://www.youtube.com/watch?v=_ZgfyTtefOA

**Comment by allusive-dev** [comment]
From what i can tell, I don't think that is possible with picom.
All the animations currently just modify the positioning and transitions for windows, what you have shown me modifies the actual geometry of the windows.
As of now i don't think this is possible but i will do some research.

**Comment by allusive-dev** [comment]
It doesn't look like I will be able to do this sadly. It probably can be done with picom but I don't have enough experience with it at this stage.
Sorry for the wait.

**Comment by SolninjaA** [comment]
If you want, you can make the windows really wobbly all the time which can achieve a similar effect (except it won't distort the actual window itself). To achieve the below video, I just disabled `animation-dampening`. Hopefully this helps.

https://github.com/allusive-dev/picom-allusive/assets/51935570/d8966228-f17e-44ad-bccc-1c4c8f14b91d
