### ISSUE TITLE
corners-rule broken if corner-radius = 0

### ISSUE THREAD

**Issue by kazuyam1negishi** [allusive-dev/picom-allusive#10]
I'm unsure if this is a bug, but I did find something strange that happens on my system. If I don't have a nonzero value for my corner-radius, corners-rule doesn't work at all, even if I give radius values to the windows I do want to be curved. I've attached part of my dotfile just in case. Hope to hear back!

CPU: Intel i5-11400H
GPU: Intel UHD / RTX 3050 Laptop
OS: Arch Linux
WM: i3
[picom.conf.txt](https://github.com/allusive-dev/picom-allusive/files/13049868/picom.conf.txt)

**Comment by allusive-dev** [comment]
Hey thanks for raising this issue.
I just tried it out now and this is the case.
The best thing I can advise is you simply set the corner-radius to 1 as this makes the corners basically not visible but still allows the use of corners-rule.

I will make the necessary changes to the Wiki.
