### ISSUE TITLE
Blur broken on 1.0.3

### ISSUE THREAD

**Issue by naan187** [allusive-dev/picom-allusive#11]
Blur seems to not be working after upgrading to 1.0.3

I tested this on all non-legacy backends, without the --experimental-backends flag of course.
![2023-10-30_13-47](https://github.com/allusive-dev/picom-allusive/assets/99505972/bbdb0bd6-0294-4d78-8b3d-b89815d0bd09)
Also notice the weirdness of the window corners? You might wanna take a look at [PR #1](https://github.com/pijulius/picom/pull/1) on the pijulius fork. This only happens on AwesomeWM

Here's my neofetch for some extra info that may or may not be needed:
![nf](https://github.com/allusive-dev/picom-allusive/assets/99505972/d83530f5-2a2d-4863-b3c1-00f02df3b2ff)

**Comment by naan187** [comment]
I've been using the pijulius fork of picom for quite some time now, so finding this was a life-saver for me. I appreciate all the work you are doing!

**Comment by allusive-dev** [comment]
> I've been using the pijulius fork of picom for quite some time now, so finding this was a life-saver for me. I appreciate all the work you are doing!

Thank you very much this means alot to me!

In 1.0.0 I switched to using a blur whitelist instead of a blacklist so windows will not blur unless you explicitly set it.
I will update the documentation soon but in the mean time here is what you should add to your config.

```
blur-rule = [
  "class_g = 'kitty'",
  "class_g = 'Emacs'",
  "class_g = 'Rofi'"
]
```

**Comment by allusive-dev** [comment]
I just noticed that issue with the corners you mentioned. I'll take a look at this as soon as I can.

At the moment I am fixing issues left right and center as they popup but this will be the first thing I do as soon as all the dumpster fires are out XD

**Comment by naan187** [comment]
Alright thank you, blur is back now.

And good luck extinguishing the dumpster fire :)

**Comment by naan187** [comment]
That's good. 
I'm already on `1.2.1`, and I haven't experienced any crashes. But the animations seem to get worse and worse over time now. I've opened [an issue](https://github.com/allusive-dev/picom-allusive/issues/14) about this
