### ISSUE TITLE
Picom Crashes - Update

### ISSUE THREAD

**Issue by allusive-dev** [allusive-dev/picom-allusive#12]
Hello Everyone,
I just wanted to make it clear that I am aware of the crashing issues that are happening.

I also want to let everyone know I am working very hard to fix this problem as soon as possible!

#### The Issue

My current assumption is that transient windows are crashing picom when they are animated. I say assumption because there was no errors setup to indentify issues with animation besides user errors under the configuration file.

I am testing fixes and will continue testing fixes until this is resolved so please hang in there.

**Comment by allusive-dev** [comment]
After testing for a while it looks like update `1.1.0` has fixed the crashing issue.

If you are still encountering this issue please let me know by commenting in this issue.

**Comment by allusive-dev** [comment]
After some more testing the crashing is is not completely fixed but it is less frequent.

I would say I have no idea what to do now. And as of writing this message I really don't know what to do.
However i have said that quite a few times to myself now and yet I keep making progress, so all I can do now is just ask that everyone please be patient!

Thank you and I will keep working hard to fix this.

**Comment by N3RDIUM** [comment]
I've observed this: Picom only crashes (on i3, at least) when I switch to an empty workspace with nothing open in it.

**Comment by allusive-dev** [comment]
> I've observed this: Picom only crashes (on i3, at least) when I switch to an empty workspace with nothing open in it.

@N3RDIUM Thanks for letting me know.
I believe that update `1.2.1` has fixed this issue, please be sure to install it as soon as you can and let me know if everything is working fine!

**Comment by allusive-dev** [comment]
> @allusive-dev Indeed, `1.2.1` works perfectly! Thank you so much for the update.

Very happy to hear!
