### ISSUE TITLE
Janky animations

### ISSUE THREAD

**Issue by naan187** [allusive-dev/picom-allusive#14]
After upgrading to `1.2.1`, the animations seem to get worse and worse over time.
Based on the fact that others seem to have not issues at all, it seems that this only happens in `AwesomeWM`

Here's a video from after about 15 minutes of using it:

https://github.com/allusive-dev/picom-allusive/assets/99505972/73659da4-f26c-46be-a6bd-dc61e26ef118

As also seen in the video, picom seems to be calling invalid X extension events `161` and `146`:
![2023-10-31_11-31](https://github.com/allusive-dev/picom-allusive/assets/99505972/8e70ccfe-fa81-4566-a4d9-832b36b44a85)

The animations are already janky right after starting picom, but (at least to my eyes) they only get worse.

**Comment by naan187** [comment]
Here's my picom config file:
[picom.conf.txt](https://github.com/allusive-dev/picom-allusive/files/13215225/picom.conf.txt)

**Comment by allusive-dev** [comment]
Probably just me but I can't see any difference in that video you attached.

Also all those Xlib errors you see are actually present in upstream picom aswell. I tested it not long ago. (yshui says that those errors are not a problem).

**Comment by allusive-dev** [comment]
Best thing I can suggest is going back through your animation setting and changing them around. 

I got a friend to test the new update and all for him the animations changed after he updated even with the same config.

Also here is a revised and cleaned version of your config, keep in mind it is good practice to end every variable with a semi-colon.

[picom.conf.txt](https://github.com/allusive-dev/picom-allusive/files/13215313/picom.conf.txt)

**Comment by naan187** [comment]
Hmm interesting, I tried the pijulius fork again, and the animations also seem to have gotten worse with that as well.
Even with the configuration I was using back then.
But it is worse with this fork.

>  keep in mind it is good practice to end every variable with a semi-colon.
That's good to know, thank you.

And thank you for the revised config

**Comment by allusive-dev** [comment]
> Hmm interesting, I tried the pijulius fork again, and the animations also seem to have gotten worse with that as well.
> Even with the configuration I was using back then.
> But it is worse with this fork.


Definitely sounds like some sort of issue with AwesomeWM. 

I'm quite sorry that is happening to you and that there isn't really anything I can think of to help.

**Comment by naan187** [comment]
Well, turns out OBS running was the issue. Sorry for the inconvenience.

**Comment by allusive-dev** [comment]
> Well, turns out OBS running was the issue. Sorry for the inconvenience.

Ah I should have remembered that OBS considerably affects the visible refresh rate (not exactly what happens but its the best way I can explain it).

No worries at all. Let me know if anything else comes up!
