### ISSUE TITLE
Transparent windows outside of `opacity-rule`

### ISSUE THREAD

**Issue by allusive-dev** [allusive-dev/picom-allusive#15]
Continuing from #3

**Comment by vinivosh** [comment]
> I have a suspicion. @vinivosh This sounds like a win-types problem possibly.
> 
> If you have a win-types config setup please attach it.
> 
> If not try this at the bottom of your config. I'm not sure which one equals what window so I just set them all lol.
> 
> ```
> wintypes:
> {
>   normal = { opacity = 1; };
>   menu = { opacity = 1; };
>   tooltip = { opacity = 1; };
>   dock = { opacity = 1; };
>   dnd = { opacity = 1; };
>   popup_menu = { opacity = 1; };
>   utility = { opacity = 1; };
>   toolbar = { opacity = 1; };
>   notification = { opacity = 1; }
> };
> ```

That was it, thank you so much! Can't believe I hadn't seen the `opacity` rules inside my wintypes, oops. Removing the entire wintypes section (or just setting the `opacity` for the wintypes `tooltip`, `popup_menu`, and `dropdown_menu`  to 1) fixed it.

I'll try to be more thorough when checking my settings now before complaining. And reading the wiki first too 😅

One last suggestion, if I may: implementing a wintype option to turn off animations (or maybe just change them?) would be really great too. Some context menus look very weird when using certain animations. I don't know if that's doable though, but it sounded like a good idea in principle.

**Comment by allusive-dev** [comment]
> That was it, thank you so much! Can't believe I hadn't seen the `opacity` rules inside my wintypes, oops. Removing the entire wintypes section (or just setting the `opacity` for the wintypes `tooltip`, `popup_menu`, and `dropdown_menu` to 1) fixed it.

Wow I guessed something first try haha. Glad to hear.

> One last suggestion, if I may: implementing a wintype option to turn off animations (or maybe just change them?) would be really great too. Some context menus look very weird when using certain animations. I don't know if that's doable though, but it sounded like a good idea in principle.

Just checked the code and this already is a feature. XD
I'll update the wiki accordingly.

The variable names are a bit different but pretty much:
```
wintypes:
{
  popup_menu = { animation = "slide-left"; }; # Set the open window animation for popup menus
};
```

```
wintypes:
{
  popup_menu = { animation-unmap = "slide-left"; }; # Set the unmap window animation for popup menus
};
```

**Comment by allusive-dev** [comment]
[New Wiki Page](https://github.com/allusive-dev/picom-allusive/wiki/8.-Wintype-Options)
