### ISSUE TITLE
AwesomeWM - Rounded Corner Glitches

### ISSUE THREAD

**Issue by allusive-dev** [allusive-dev/picom-allusive#16]
@naan187

I just released a test build to try to fix the problem.

If you can build the package manually please build [this release](https://github.com/allusive-dev/picom-allusive-testing/archive/refs/tags/3.0.0.zip).

If you cannot build manually please let me know.

If you are able to build it with no issues let me know if that update has fixed the problem or if anything else happens.
(Do not worry about the following errors if they come up in the console. 
_gl_ffill ERROR - Invalid framebuffer
Xlib: invalid extension event
win_set_flags - Flags set on destroyed window.
)

**Comment by naan187** [comment]
That fixed it.
Thank you :D

**Comment by allusive-dev** [comment]
> That fixed it. Thank you :D

Awesome, I'll push it to the main branch now.

**Comment by allusive-dev** [comment]
@naan187 
Just needed to let you know as of `1.2.4` you need to add this line to your config to fix the corner issues!
This is because the code I changed to fix the issue has caused problem for people on other WM's

```
wm-support = "awesome";
```

**Comment by naan187** [comment]
Alright thank you for letting me know.

But wouldn't it be possible to detect the current session with the `DESKTOP_SESSION` envionment variable?
Like, apply the fix only if `DESKTOP_SESSION` is equal to `awesome` (if building awesomewm from source) or `awesomex11` (if using the copr repo).
Seems very inconvenient to do it through an option since people might wanna use the same configuration for multiple WM's

**Comment by naan187** [comment]
I don't know how awesome handles `DESKOTP_SESSION` differently for the aur package or the stable 4.3 packages though.
Might be wise to just look if `awesome` is contained in the `DESKTOP_SESSION` string

**Comment by allusive-dev** [comment]
> Alright thank you for letting me know.
> 
> But wouldn't it be possible to detect the current session with the `DESKTOP_SESSION` envionment variable?
> Like, apply the fix only if `DESKTOP_SESSION` is equal to `awesome` (if building awesomewm from source) or `awesomex11` (if using the copr repo).
> Seems very inconvenient to do it through an option since people might wanna use the same configuration for multiple WM's

I'll look into it

**Comment by allusive-dev** [comment]
@naan187
Good news. After quite a bit of research `1.4.0` has released and your window manger is now automatically detected and has patches applied.
With this update `wm-support` is now deprecated.
