### ISSUE TITLE
[Question] Specific support for bspwm

### ISSUE THREAD

**Issue by vihu** [allusive-dev/picom-allusive#27]
Hello,

This is maybe more of a question rather than a bug/feature request. I noticed in the latest commits that some patches for dwm were added, I was wondering whether something similar is potentially required for [bspwm](https://github.com/baskerville/bspwm).

Thanks!

**Comment by allusive-dev** [comment]
Hey @vihu 
What patches were you thinking bspwm needed or what issues are you experiencing that you think the dwm patches would fix?

**Comment by vihu** [comment]
> Hey @vihu What patches were you thinking bspwm needed or what issues are you experiencing that you think the dwm patches would fix?

I don't really notice any suspicious bugs to be clear. I mostly just wanted to ask, if there's no need for bspwm specific patches then we can just close this. Thanks for answering!

**Comment by allusive-dev** [comment]
> If there's no need for bspwm specific patches then we can just close this. Thanks for answering!

The only issues `dwm` patches fix is unfocused windows not properly being considered unfocused.
