### ISSUE TITLE
GLX error at line 699

### ISSUE THREAD

**Issue by gargulaonline** [allusive-dev/picom-allusive#31]
**What is the issue**
Ouput the message GLX error at line 699 continue on terminal. 

**What did you expect**
I thing no problem with picom allusive, maybe, but the message is someone not cool. 

**Relevant Images or Videos:**
![bug-allusive](https://github.com/allusive-dev/picom-allusive/assets/114536673/5c3a4aed-52cc-46cd-a4a8-0872f38ee09f)

**Your configuration**
My config
[https://raw.githubusercontent.com/gargulaonline/dotfiles/main/bspwm/picom.conf](https://raw.githubusercontent.com/gargulaonline/dotfiles/main/bspwm/picom.conf)

**Package Version:**
v1.4.3
**Build Method:**
Install  via aur helper paru
**WM:**
I use bspwm with nvidia driver proprietary.

**Comment by allusive-dev** [comment]
Those errors are present on upstream as well. You can ignore them nothing is broken.
