### ISSUE TITLE
repeated GLX errors

### ISSUE THREAD

**Issue by naan187** [allusive-dev/picom-allusive#35]
**What is the issue**
A bunch of errors get repeatedly thrown, all related to glx.
May be related to #31 , doesn't seem likely though, since there are a lot less errors in that issue and there are no Xlib errors here

**What did you expect**
No errors

**Relevant Images or Videos:**
![2023-11-14_16-20](https://github.com/allusive-dev/picom-allusive/assets/99505972/bc4feef9-ee21-4884-b991-c191b1bb9d23)
![2023-11-14_16-18](https://github.com/allusive-dev/picom-allusive/assets/99505972/92404f06-1ba9-49f3-8348-23884c103d60)

**Your configuration**
[picom.conf.txt](https://github.com/allusive-dev/picom-allusive/files/13352388/picom.conf.txt)

**Package Version:** 1.5.0, also happens on 1.4.3

**Build Method:** as described in the readme
**WM:** awesomewm git version

**Comment by allusive-dev** [comment]
@naan187 
It is the same as #31 
Some people with some setup's have more errors than others. Soon I will work on silencing unimportant errors such as some of these.
