### ISSUE TITLE
setting workspace switch animation doesnt do anything

### ISSUE THREAD

**Issue by thecodsman** [allusive-dev/picom-allusive#4]
setting `animation-for-workspace-switch-in` and `animation-for-workspace-switch-out` has no effect

here is my config file
```
corner-radius = 5
corner-radius-rules = "10:class_g *?= 'dmenu'"
rounded-corners-exclude = "class_g = 'dwm'";

shadow = true

animations = true
animation-for-open-window = "zoom"
animation-for-workspace-switch-in = "slide-down"
animation-for-workspace-switch-out = "slide-up"
fading = true
fade-in-step = 0.03
fade-out-step = 0.03

backend = "glx";
use-damage = false;
```
when I switch workspaces it still goes to the left

distro: artix linux (with runit)
WM: dwm

**Comment by allusive-dev** [comment]
Yeah that's kinda how it works sorry.
If you are switching between monitor workspaces it will simply move towards that monitor. The animation will only play when switching between virtual workspaces. So like if you have click able workspaces then it should do the set animation.

**Comment by allusive-dev** [comment]
As an example when switching between 2 work-spaces on xmonad on the same monitor not between my second one it plays the animation.

Thanks for posting and issue and let me know if you need anymore assistance.

**Comment by allusive-dev** [comment]
When trying this myself the animation dosen't seem to play 100% of the time. Is it playing at all for you?

**Comment by thecodsman** [comment]
it always plays the default animation (or atleast what I assume is the default) which is going to and from the left side of my screen

**Comment by allusive-dev** [comment]
Yeah, I am sorry about that. I think the issue may like you said just be your WM/config.

**Comment by thecodsman** [comment]
@allusive-dev update: I was curious so I install i3 and switching the workspace animation works so... I guess its just a dwm thing

**Comment by allusive-dev** [comment]
> @allusive-dev update: I was curious so I installed i3 and switching the workspace animation works so... I guess its just a dwm thing (im still using dwm because I dont like i3)

Hey, Thanks for letting me know.
