### ISSUE TITLE
[IMPLEMENTED] Rules For Rounded Corners

### ISSUE THREAD

**Issue by thecodsman** [allusive-dev/picom-allusive#5]
how do you add rules for rounded corners
(like opacity rule but for rounded corners) and if it is currently not possible
could you add it

**Comment by allusive-dev** [comment]
```
rounded-corners-exclude = [
  "class_g = 'Alacritty'",
];
```

**Comment by allusive-dev** [comment]
I have also just now updated the wiki with this information.

**Comment by thecodsman** [comment]
> ```
> rounded-corners-exclude = [
>   "class_g = 'Alacritty'",
> ];
> ```

thats excluding rounded corners entirely from that thing but what im saying is that you can change how rounded
the corners are for a specific thing like in regular picom
you can do
```
corner-radius-rule = [
 "10:class_g = 'dmenu'"
]
```
and dmenu would have a corner radius of 10 (even if you set your corner radius to something else)

**Comment by allusive-dev** [comment]
Oh. I see.
I don't think that is a feature of this picom fork but you could try that code snippet you sent. 
Otherwise I can try to integrate this feature.

**Comment by thecodsman** [comment]
I do have it in my config and it doesnt work (ive also tried corner-radius-rules rounded-corners-rule and rounded-corners-rules)

**Comment by allusive-dev** [comment]
Alright i will take a look at whether I can integrate it sometime today.

**Comment by thecodsman** [comment]
also could you add rules for animations (where you could change things like not only the animation type but also the mass and stuff) also animation exclude

**Comment by allusive-dev** [comment]
> also could you add rules for animations (where you could change things like not only the animation type but also the mass and stuff) also animation exclude

I can have a go at animation exclude but have you read the wiki concerning the other stuff?

**Comment by thecodsman** [comment]
I dont see anything about animation rules but I might be dumb

**Comment by thecodsman** [comment]
it seems like anything with multiple options doesnt have a rule list

**Comment by allusive-dev** [comment]
I can try working on animation rules but i need a bit more explanation on what you are looking for. Do you have discord/matrix?

[Contacts](https://github.com/allusive-dev#contact-me)

**Comment by thecodsman** [comment]
like you could do
```
animation-rules:
[
 "mass=10, dampening=20, animation-for-window-open='slide-up':class_g = 'dmenu'"
 "mass=0, dampening=0, animation-for-window-open='slide-left', animation-for-window-close='slide-right':class_g = 'firefox'"
]
```
so each option would be seperated by a comma and then you put a colon and the condition

**Comment by allusive-dev** [comment]
Hm.
Well you see, that is very complicated and something I definitely cannot do.
Most I can maybe do is make a ruleset for windows that are excluded from being animated.
Sorry.

**Comment by thecodsman** [comment]
I understand, it wasnt a feature I wanted that bad anyways. animation exclude is more what I want

**Comment by allusive-dev** [comment]
I hate to like have an ego but I actually just got `animation-exclude` to work first try.

Just to check  would you like me to make multiple exclude list for each type of animation? e.g. `open, unmap`

**Comment by thecodsman** [comment]
if you can it it would be cool to have separate exclude list for each type but if you cant its not a big deal I dont think

**Comment by thecodsman** [comment]
sorry I keep giving you more features to add lol

**Comment by allusive-dev** [comment]
Hm yeah corner-radius-rule should be fun, I'll see what I can do.

I should be able to do 2 different exclude lists.

> sorry I keep giving you more features to add lol

No problem, gives me something to do when I am not working.

**Comment by allusive-dev** [comment]
Good news i got both the animation exclude rule sets working but I may not be able to do the corner-radius-rule sadly due to the way it is integrated. I'll let you know if i make progress on it in the future.

**Comment by thecodsman** [comment]
ok cool

**Comment by thecodsman** [comment]
lets goooooooooo thank you

**Comment by thecodsman** [comment]
@allusive-dev I tested it and it doesnt work on dwm :( because I tried it on i3 and it worked. Also its worth noting that in regular picom the corner-radius-rule worked

**Comment by thecodsman** [comment]
nvm it just started working suddenly

**Comment by allusive-dev** [comment]
> nvm it just started working suddenly

Awesome, I am glad to hear
