### ISSUE TITLE
I found out what clamping does lol

### ISSUE THREAD

**Issue by thecodsman** [allusive-dev/picom-allusive#6]
@allusive-dev I found out what animation-clamping does. I was messing around with trying to get that bouncy effect to the animations and I just couldnt so then I tried to disable animation clamping and... (I had my mass at 10 at the time)
https://youtu.be/u96Vj6If1EY (I had to upload it to youtube because the file is too big for github)

**Comment by allusive-dev** [comment]
Ah. Thanks so much, I will update the wiki.

Awesome linux setup btw. I love those gold colors!

**Comment by thecodsman** [comment]
> Awesome linux setup btw. I love those gold colors!
thanks haha I used pywal to generate a colorscheme off of some random fall photo off the internet

**Comment by thecodsman** [comment]
> Awesome linux setup btw. I love those gold colors!
thanks haha I used pywal to generate a colorscheme off of some random fall photo off the internet
